### ISSUE TITLE
Can we move to Neovim and drop support for VIM?

### ISSUE THREAD

**Issue by linrongbin16** [linrongbin16/fzfx.vim#109]
Hi, since less and less people use VIM, can we move to Neovim only? I will re-write this plugin with lua, but the idea is still heavily hack into fzf.vim and leverage its script local utility functions.

**Comment by linrongbin16** [comment]
I create a lua version here: https://github.com/linrongbin16/fzfx.nvim.

**Comment by PEMessage** [comment]
这个仓库可以维护现有的功能即可, 新的功能就在nvim下开发就行了
