### ISSUE TITLE
How to get preview windows?

### ISSUE THREAD

**Issue by reckoner** [linrongbin16/fzfx.vim#60]
In your video demos, there is a preview window that shows context for many of the results. How do you enable this?

**Comment by linrongbin16** [comment]
this plugin respect fzf.vim global variables, so you can set 

please see: https://github.com/linrongbin16/lin.nvim/blob/a9c7129e44a39755030e40ceb78a0e00116c0072/repo/junegunn/fzf.vim/init.vim#L10

**Comment by reckoner** [comment]
Thank you!
